### ISSUE TITLE
changes to configmap are not synced to datadog api

### ISSUE THREAD

**Issue by farshad-hobsons** [FairwindsOps/astro#119]
### Steps to reproduce

Deployed astro using the helm chart with the following command:
```bash
helm --tiller-namespace ops --namespace ops upgrade um-astro fairwinds-stable/astro --debug -i --set custom_config.enabled=true --set secret.create=false --set secret.name=um-datadog-astro-secret -f custom-config.yaml
```
The ^^ deploys the following versions:
```bash
# helm --tiller-namespace ops list um-astro --output yaml
Next: ""
Releases:
- AppVersion: 1.5.3
  Chart: astro-1.0.4
  Name: um-astro
  Namespace: ops
  Revision: 7
  Status: DEPLOYED
  Updated: Mon Jul 13 21:33:48 2020
```
The docker image deployed is: `image: quay.io/fairwinds/astro:v1.5.3`

Data in `custom-config.yaml`
```yaml
custom_config:
  enabled: false
  data: |
    ---
    cluster_variables:
      warning_notifications: "@myemail@XXX.com"
    rulesets:
    - type: deployment
      match_annotations:
        - name: astro/owner
          value: astro
      monitors:
        deploy-replica-alert:
          name: "Deployment Replica Alert - {{ .ObjectMeta.Name }}"
          type: metric alert
          query: "max(last_10m):max:kubernetes_state.deployment.replicas_available{deployment:{{ .ObjectMeta.Name }},namespace:{{ .ObjectMeta.Namespace }}} <= 0"
          message: |-
            {{ "{{#is_alert}}" }}
            Available replicas is currently 0 for {{ .ObjectMeta.Name }}
            {{ "{{/is_alert}}" }}
            {{ "{{^is_alert}}" }}
            Available replicas is no longer 0 for {{ .ObjectMeta.Name }}
            {{ "{{/is_alert}}" }}
            {{ ClusterVariables.warning_notifications }}
          tags: []
          options:
            no_data_timeframe: 60
            notify_audit: false
            notify_no_data: false
            renotify_interval: 5
            new_host_delay: 5
            evaluation_delay: 300
            timeout: 300
            escalation_message: ""
            threshold_count:
              critical: 0
            require_full_window: true
            locked: false

```
When I make a configuration change to `custom-config.yaml` e.g. `last_5m` to `last_10m` and run the helm upgrade command again, the configmap is updated appropriately but the changes never make it Datadog monitor (it continues to show `last_5m`)

Configmap after helm upgrade command:
```bash
$kubectl -nops get cm um-astro-data -oyaml | grep query
          query: "max(last_10m):max:kubernetes_state.deployment.replicas_available{deployment:{{ .ObjectMeta.Name }},namespace:{{ .ObjectMeta.Namespace }}} <= 0"
```
pods logs after helm upgrade:
```txt
time="2020-07-13T21:53:07Z" level=info msg="Loading rulesets from /etc/config/config.yml"
time="2020-07-13T21:54:07Z" level=info msg="Loading rulesets from /etc/config/config.yml"
time="2020-07-13T21:55:07Z" level=info msg="Loading rulesets from /etc/config/config.yml"
```

Also, the configmap changes are only synced if I bounce the old pods.
