### ISSUE TITLE
monitors of type "log alert" are created and deleted immediately in Datadog

### ISSUE THREAD

**Issue by faarshad** [FairwindsOps/astro#120]
dockerimage: v1.6.0
k8s version: 1.15.11

I am using the custom config as follows:
```yaml
custom_config:
  enabled: true
  data: |
    ---
    cluster_variables:
      warning_notifications: "@myemail@myemail.com"
      cluster_name: "sandbox"
    rulesets:
    - type: deployment
      match_annotations:
        - name: astro/owner
          value: falco
      monitors:
        falco-alert:
          name: "[ASTRO TEST] Falco Alert: - {{ ClusterVariables.cluster_name }} "
          type: log alert
          query: "logs(\"service:falco (\"A shell was spawned in a container with an attached terminal\" OR \"Privileged container started\" OR \"File below /etc opened for writing\")\").index(\"main\").rollup(\"count\").last(\"5m\") > 10"
          message: |-
            {{ ClusterVariables.warning_notifications }}
          tags: []
          options:
            no_data_timeframe: 60
            notify_audit: false
            notify_no_data: false
            renotify_interval: 5
            new_host_delay: 5
            evaluation_delay: 300
            timeout: 300
            escalation_message: ""
            threshold_count:
              critical: 10
              warning: 5
            require_full_window: true
            locked: false
```
On adding an annotation `astro/owner=falco` to a deployment, the logs show that a datadog monitor is created and deleted right after its creation

Logs:
====
```logs
time="2020-07-16T19:52:41Z" level=debug msg="deployment/ops-managed/stateful-sample-app-drupal-example has been updated."
time="2020-07-16T19:52:41Z" level=debug msg="Handler got an OnUpdate event of type deployment"
time="2020-07-16T19:52:41Z" level=debug msg="Loading rulesets from /etc/config/config.yml"
time="2020-07-16T19:52:41Z" level=debug msg="Reconcile monitor [ASTRO TEST] Falco Alert: - sandbox "
time="2020-07-16T19:52:41Z" level=debug msg="Update templated monitor: [ASTRO TEST] Falco Alert: - sandbox "
time="2020-07-16T19:52:41Z" level=debug msg="deployment/ops-managed/stateful-sample-app-drupal-example has been updated."
time="2020-07-16T19:52:41Z" level=info msg="Creating new monitor: [ASTRO TEST] Falco Alert: - sandbox "
time="2020-07-16T19:52:41Z" level=info msg="Removing monitor: [ASTRO TEST] Falco Alert: - sandbox"
time="2020-07-16T19:52:41Z" level=debug msg="Handler got an OnUpdate event of type deployment"
time="2020-07-16T19:52:41Z" level=debug msg="Old annotations match new, not updating: ops-managed/stateful-sample-app-drupal-example"
```

My expectation was that the monitor should only be deleted when the annotation is removed
