### ISSUE TITLE
reload isn't creating or deleting monitors

### ISSUE THREAD

**Issue by isaaguilar** [FairwindsOps/astro#144]
The 1-minute reload is not triggering the addition and removal of new monitors. Is this expected behavior? 

I can confirm that the updates to some of the fields are working, like modifying the `message` of a monitor.

**Comment by lucasreed** [comment]
Hello! Could you please provide more information? Did you update the configuration via updating the `ConfigMap` or did you update annotations and expect a monitor to change.

If you updated the monitor configuration `ConfigMap` you will need to restart the pods in the deployment. A recent change in the helm chart should do this for you if you are modifying it that way.

**Comment by lucasreed** [comment]
Here is the change to the chart I referenced: https://github.com/FairwindsOps/charts/pull/376

**Comment by isaaguilar** [comment]
Hi @lucasreed. I'm installing the app astro:v1.6.0 via the helm chart version 1.0.5. But I then I had to patch the `volumes`/`volumeMounts` to point to a different monitor configuration `ConfigMap` that I modify outside the helm chart. I made sure to point the `DEFINITIONS_PATH` to the mounted file.  

Everything works, as in monitors are added and removed when I restart the pods. The way I thought reload would work was when I modified the monitor configuration `ConfigMap`, Astro would reload the monitor configuration and handle adding and removing without having to restart the pod.

**Comment by isaaguilar** [comment]
Since reload wasn't working how I imagined it would, I thought maybe I can add a sidecar to "restart" the pod when it detects changes to the `ConfigMap`. Something like this should do the trick, albeit a little "hacky." And permissions would need to be granted which is always a little sketchy. 

```yaml
      containers:
       #(...main astro container)
      - args:
        - cp /etc/config/config.yml /tmp/; until ! diff /etc/config/config.yml /tmp/config.yml;do 
          sleep 30;done; kubectl delete pod "$HOSTNAME"
        command:
        - /bin/sh
        - -c
        image: isaaguilar/kubectl:latest
        imagePullPolicy: IfNotPresent
        name: isapod
        volumeMounts:
        - mountPath: /etc/config
          name: config-data
```

I'm sure there's a better way but for now I'll try this out as a stop gap.
