### ISSUE TITLE
The options `require_full_window` isn't working

### ISSUE THREAD

**Issue by isaaguilar** [FairwindsOps/astro#145]
I'm using `image: quay.io/fairwinds/astro:v1.6.0` version of the Astro controller and I'm having an issue with the `require_full_window` options in all of my monitors.  Setting the options for `require_full_window: true` in my astro-data ConfigMap is not translating to the correct setting in the actual DD monitor.  

Here's a snippet of a monitor that I'm trying to make have a `require_full_window: true`. The monitor gets created with all the right settings except that one. 

```
# ...
    - monitors:
        deployment:
          message: |-
            {{#is_alert}}
            Daemonset 'aws-node' has an issue
            {{/is_alert}}

            {{#is_recovery}}
            Daemonset 'aws-node' ready count recovered
            {{/is_recovery}}
          name: 'aws-node Daemonset Alert'
          options:
            evaluation_delay: 0
            locked: false
            no_data_timeframe: 60
            notify_audit: false
            notify_no_data: false
            renotify_interval: 0
            require_full_window: true
            threshold_count:
              critical: 0
          query: min(last_10m):abs( max:kubernetes_state.daemonset.desired{cluster_name:my-cluster,daemonset:aws-node} - max:kubernetes_state.daemonset.ready{cluster_name:my-cluster,daemonset:aws-node} ) > 0
          type: metric alert
      type: static
```
